#!/usr/bin/env python3
"""
Post-process vue_ensemble_interactive_v3.drawio: English → French
Updates date to v0.7 - 2026-03-09
"""
import re

TRANSLATIONS = [
    # Title & header
    ("QMS MAP ISO 9001:2015", "CARTOGRAPHIE SMQ ISO 9001:2015"),
    ("GLOBAL OVERVIEW v3", "VUE D'ENSEMBLE v3"),
    ("Industrial follow-up &amp; worldwide sourcing", "Suivi industriel et sourcing mondial"),
    ("Industrial follow-up &amp;amp; worldwide sourcing", "Suivi industriel et sourcing mondial"),
    ("v0.7 - 2026-03-05", "v0.7 — 2026-03-09"),
    ("2026-03-05T18:00:00.000Z", "2026-03-09T10:00:00.000Z"),
    ("2026-03-05T14:00:00.000Z", "2026-03-09T10:00:00.000Z"),
    ("Click on each element to access details", "Cliquez sur chaque element pour acceder aux details"),
    ("Click on each BLOC to view details", "Cliquez sur chaque BLOC pour voir les details"),
    ("Click on each colored block to navigate to the detailed sub-diagram.", "Cliquez sur chaque bloc colore pour naviguer vers le sous-diagramme detaille."),
    ("Orange dashed arrows show the inter-role operational flow.", "Les fleches orange en pointilles montrent le flux operationnel inter-roles."),

    # Stakeholders
    ("CUSTOMERS", "CLIENTS"),
    ("(International)", "(Internationaux)"),
    ("Needs", "Besoins"),
    ("Requirements", "Exigences"),
    ("Orders", "Commandes"),
    ("Satisfaction", "Satisfaction"),
    ("Conforming products", "Produits conformes"),
    ("On-time delivery", "Livraison ponctuelle"),
    ("SUPPLIERS", "FOURNISSEURS"),
    ("Production", "Production"),
    ("Delivery", "Livraison"),
    ("CUSTOMER", "CLIENT"),
    ("Order", "Commande"),

    # Swimlane headers
    ("MANAGEMENT", "DIRECTION"),
    ("01 SALES — Commercial Role", "01 VENTES — Role Commercial"),
    ("02 MANUFACTURE — Procurement Role", "02 FABRICATION — Role Achats"),
    ("03 DELIVERY — Logistics Role", "03 LIVRAISON — Role Logistique"),
    ("04 QUALITY — Quality Role", "04 QUALITE — Role Qualite"),
    ("SUPPORT", "SUPPORT"),
    ("SALES", "VENTES"),
    ("MANUFACTURE", "FABRICATION"),
    ("DELIVERY", "LIVRAISON"),
    ("QUALITY", "QUALITE"),

    # Process names
    ("Leadership &amp;amp; Management", "Leadership &amp;amp; Pilotage"),
    ("Leadership &amp; Management", "Leadership &amp; Pilotage"),
    ("Policy | Objectives | Risks", "Politique | Objectifs | Risques"),
    ("Management review | KPIs", "Revue direction | KPIs"),
    ("Continuous Improvement", "Amelioration Continue"),
    ("PDCA | Annual program", "PDCA | Programme annuel"),
    ("Commercial", "Commercial"),
    ("Quotation | Contract", "Devis | Contrat"),
    ("Follow-up | Satisfaction", "Suivi | Satisfaction"),
    ("Procurement &amp;amp;", "Achats &amp;amp;"),
    ("Procurement &amp;", "Achats &amp;"),
    ("Subcontracting", "Sous-traitance"),
    ("Evaluation | SQA | Follow-up", "Evaluation | AQF | Suivi"),
    ("Quality Control", "Controle Qualite"),
    ("IPC | DUPRO | PSI", "IPC | DUPRO | PSI"),
    ("NC | Corrective actions", "NC | Actions correctives"),
    ("Logistics &amp;amp;", "Logistique &amp;amp;"),
    ("Logistics &amp;", "Logistique &amp;"),
    ("Transport | Customs", "Transport | Douane"),
    ("Document Management", "Gestion Documentaire"),
    ("Create | Control | Archive", "Creer | Maitriser | Archiver"),
    ("Competence Management", "Gestion des Competences"),
    ("Matrix | Training", "Matrice | Formation"),

    # BLOC names
    ("BLOC 1 - ORDER RECEPTION", "BLOC 1 - RECEPTION COMMANDE"),
    ("BLOC 2 - ORDER SHEET CREATION", "BLOC 2 - CREATION FICHE COMMANDE"),
    ("BLOC 3 - TRANSPORT SHEET CREATION", "BLOC 3 - CREATION FICHE TRANSPORT"),
    ("BLOC 4 - TECHNICAL STUDY SUPPLIERS", "BLOC 4 - ETUDE TECHNIQUE FOURNISSEURS"),
    ("BLOC 5 - ORDER VALIDATION", "BLOC 5 - VALIDATION COMMANDE"),
    ("BLOC 6 - PRODUCTION &amp;amp; QUALITY", "BLOC 6 - PRODUCTION &amp;amp; QUALITE"),
    ("BLOC 6 - PRODUCTION &amp; QUALITY", "BLOC 6 - PRODUCTION &amp; QUALITE"),
    ("BLOC 7 - DELIVERY &amp;amp; CUSTOMS", "BLOC 7 - LIVRAISON &amp;amp; DOUANE"),
    ("BLOC 7 - DELIVERY &amp; CUSTOMS", "BLOC 7 - LIVRAISON &amp; DOUANE"),
    ("BLOC 8 - GOODS ACCEPTANCE &amp;amp; CLOSURE", "BLOC 8 - ACCEPTATION MARCHANDISE &amp;amp; CLOTURE"),
    ("BLOC 8 - GOODS ACCEPTANCE &amp; CLOSURE", "BLOC 8 - ACCEPTATION MARCHANDISE &amp; CLOTURE"),
    ("Order Reception — Details", "Reception Commande — Details"),
    ("Order Sheet — Details", "Fiche Commande — Details"),
    ("Transport Sheet — Details", "Fiche Transport — Details"),
    ("Technical Study — Details", "Etude Technique — Details"),
    ("Order Validation — Details", "Validation Commande — Details"),
    ("Production &amp;amp; Quality — Details", "Production &amp;amp; Qualite — Details"),
    ("Production &amp; Quality — Details", "Production &amp; Qualite — Details"),
    ("Delivery &amp;amp; Customs — Details", "Livraison &amp;amp; Douane — Details"),
    ("Delivery &amp; Customs — Details", "Livraison &amp; Douane — Details"),
    ("Goods Acceptance — Details", "Acceptation Marchandise — Details"),

    # BLOC overview labels
    ("BLOC 1", "BLOC 1"),
    ("Order<br>Reception", "Reception<br>Commande"),
    ("Order<br>Sheet", "Fiche de<br>Commande"),
    ("Order<br>Validation", "Validation<br>Commande"),
    ("Invoice +<br>Customer info", "Facture +<br>Info client"),
    ("Invoice | Customs<br>Payment | Closure", "Facture | Douane<br>Paiement | Cloture"),
    ("Technical Study<br>Suppliers", "Etude Technique<br>Fournisseurs"),
    ("Supplier<br>Production", "Production<br>Fournisseur"),
    ("Transport<br>Sheet", "Fiche de<br>Transport"),
    ("Delivery<br>Customs", "Livraison<br>Douane"),
    ("Conformity<br>Validation", "Validation<br>Conformite"),
    ("Goods<br>Acceptance", "Acceptation<br>Marchandise"),

    # Process detail steps
    ("Analyze context", "Analyser le contexte"),
    ("Internal/external issues", "Enjeux internes/externes"),
    ("Interested parties", "Parties interessees"),
    ("Define policy", "Definir la politique"),
    ("Management commitment", "Engagement direction"),
    ("Customer focus", "Orientation client"),
    ("Set objectives", "Fixer les objectifs"),
    ("Measurable, consistent", "Mesurables, coherents"),
    ("with policy", "avec la politique"),
    ("Allocate resources", "Allouer les ressources"),
    ("Human, material", "Humaines, materielles"),
    ("financial", "financieres"),
    ("Manage risks", "Gerer les risques"),
    ("Risk matrix", "Matrice des risques"),
    ("Opportunities", "Opportunites"),
    ("Management review", "Revue de direction"),
    ("Periodic review", "Revue periodique"),
    ("Decisions", "Decisions"),
    ("Improve", "Ameliorer"),
    ("Preventive actions", "Actions preventives"),
    ("Monitor KPIs", "Surveiller les KPIs"),
    ("Dashboards", "Tableaux de bord"),
    ("Performance monitoring", "Suivi performance"),

    # P01 steps
    ("Request reception", "Reception demande"),
    ("Email / phone", "Email / telephone"),
    ("CRM registration", "Enregistrement CRM"),
    ("Feasibility analysis", "Analyse faisabilite"),
    ("Technical verification", "Verification technique"),
    ("Supplier capacity", "Capacite fournisseur"),
    ("Quotation &amp;amp; proposition", "Devis &amp;amp; proposition"),
    ("Quotation &amp; proposition", "Devis &amp; proposition"),
    ("Price, deadline, conditions", "Prix, delais, conditions"),
    ("Sent to customer", "Envoye au client"),
    ("Contract review", "Revue de contrat"),
    ("Requirements validation", "Validation des exigences"),
    ("Commercial agreement", "Accord commercial"),
    ("Confirmed order", "Commande confirmee"),
    ("PO received", "BC recu"),
    ("Process launch", "Lancement processus"),
    ("Order follow-up", "Suivi commande"),
    ("Dashboard", "Tableau de bord"),
    ("Customer communication", "Communication client"),
    ("Invoicing", "Facturation"),
    ("Customer invoice", "Facture client"),
    ("Customs declaration", "Declaration douaniere"),
    ("Customer survey", "Enquete client"),
    ("Feedback analysis", "Analyse retours"),

    # P02 steps
    ("Identify suppliers", "Identifier fournisseurs"),
    ("Market research", "Recherche marche"),
    ("Selection criteria", "Criteres de selection"),
    ("Evaluate &amp;amp; qualify", "Evaluer &amp;amp; qualifier"),
    ("Evaluate &amp; qualify", "Evaluer &amp; qualifier"),
    ("Supplier audit", "Audit fournisseur"),
    ("Evaluation grid", "Grille evaluation"),
    ("Sign SQA", "Signer AQF"),
    ("Quality Agreement", "Accord Qualite"),
    ("Supplier", "Fournisseur"),
    ("Issue order", "Emettre commande"),
    ("Supplier PO", "BC fournisseur"),
    ("Specifications", "Specifications"),
    ("Track production", "Suivre production"),
    ("Supplier contact", "Contact fournisseur"),
    ("Production status", "Statut production"),
    ("Re-evaluate suppliers", "Reevaluer fournisseurs"),
    ("Annual review", "Revue annuelle"),
    ("QCDM rating", "Notation QCDM"),
    ("Manage supplier NCs", "Gerer les NC fournisseur"),
    ("NC sheets", "Fiches NC"),
    ("Action follow-up", "Suivi des actions"),
    ("Panel A/B/C", "Panel A/B/C"),
    ("Classification", "Classification"),
    ("suppliers", "fournisseurs"),

    # P03 steps
    ("Plan QC", "Planifier CQ"),
    ("Inspection planning", "Planification inspections"),
    ("Assignment", "Attribution"),
    ("Initial Production", "Controle Initial"),
    ("Check", "Controle"),
    ("During Production", "En Cours de"),
    ("Inspection", "Inspection"),
    ("Pre-Shipment", "Pre-Expedition"),
    ("Loading Check", "Loading Check"),
    ("Loading check", "Controle chargement"),
    ("Container", "Conteneur"),
    ("Detect NC", "Detecter NC"),
    ("Non-conformities", "Non-conformites"),
    ("Inspection report", "Rapport inspection"),
    ("Process NC", "Traiter NC"),
    ("Accept / rework", "Accepter / retoucher"),
    ("reject", "rejeter"),
    ("Corrective actions", "Actions correctives"),
    ("Root cause", "Cause racine"),
    ("Action plan", "Plan d'action"),

    # P04 steps
    ("Plan shipment", "Planifier expedition"),
    ("Date, volume", "Date, volume"),
    ("Transport mode", "Mode transport"),
    ("Carrier selection", "Selection transporteur"),
    ("Transport quotation", "Devis transport"),
    ("Provider choice", "Choix prestataire"),
    ("Transport documents", "Documents transport"),
    ("BL, packing list", "BL, liste de colisage"),
    ("Certificates", "Certificats"),
    ("Shipment tracking", "Suivi expedition"),
    ("Tracking", "Tracking"),
    ("Communication", "Communication"),
    ("Customs management", "Gestion douaniere"),
    ("Customs agent", "Agent en douane"),
    ("Delivery confirmation", "Confirmation livraison"),
    ("Customer receipt", "Reception client"),
    ("Proof of delivery", "Preuve livraison"),
    ("Archiving", "Archivage"),
    ("Complete file", "Dossier complet"),
    ("Document retention", "Conservation documents"),

    # PS01 steps
    ("Create documents", "Creer les documents"),
    ("Procedures, forms", "Procedures, formulaires"),
    ("Instructions", "Instructions"),
    ("Verify &amp;amp; approve", "Verifier &amp;amp; approuver"),
    ("Verify &amp; approve", "Verifier &amp; approuver"),
    ("Technical review", "Revue technique"),
    ("Management approval", "Approbation direction"),
    ("Distribute", "Distribuer"),
    ("Making available", "Mise a disposition"),
    ("Control versions", "Maitriser les versions"),
    ("Revision index", "Indice de revision"),
    ("Change history", "Historique modifications"),
    ("Archive", "Archiver"),
    ("Retention", "Conservation"),
    ("Retention period", "Duree de conservation"),
    ("Audit conformity", "Audit conformite"),
    ("Verification", "Verification"),
    ("Document gaps", "Ecarts documentaires"),
    ("Improve doc. system", "Ameliorer syst. doc."),
    ("User feedback", "Retours utilisateurs"),
    ("Simplification", "Simplification"),

    # PS02 steps
    ("Identify competences", "Identifier competences"),
    ("Skills mapping", "Cartographie competences"),
    ("Requirements", "Exigences"),
    ("Competence matrix", "Matrice de competences"),
    ("Current level", "Niveau actuel"),
    ("Gap analysis", "Analyse des ecarts"),
    ("Training plan", "Plan de formation"),
    ("Training needs", "Besoins formation"),
    ("Annual plan", "Plan annuel"),
    ("Execute training", "Executer formation"),
    ("Training delivery", "Realisation formation"),
    ("Records", "Enregistrements"),
    ("Evaluate effectiveness", "Evaluer efficacite"),
    ("Post-training review", "Revue post-formation"),
    ("Skill update", "Mise a jour competences"),

    # PS03 steps
    ("Collect data", "Collecter les donnees"),
    ("KPIs, audits", "KPIs, audits"),
    ("Customer feedback", "Retours clients"),
    ("Analyze performance", "Analyser performance"),
    ("Trend analysis", "Analyse tendances"),
    ("Gap identification", "Identification ecarts"),
    ("Plan improvements", "Planifier ameliorations"),
    ("Prioritization", "Priorisation"),
    ("Resource allocation", "Allocation ressources"),
    ("Implement actions", "Mettre en oeuvre"),
    ("Execute plan", "Executer le plan"),
    ("Monitor progress", "Suivre les progres"),
    ("Verify results", "Verifier les resultats"),
    ("Effectiveness check", "Controle efficacite"),
    ("Target comparison", "Comparaison objectifs"),
    ("Standardize", "Standardiser"),
    ("Update procedures", "Mettre a jour procedures"),
    ("Share lessons", "Partager les lecons"),

    # Chain pages
    ("CHAIN-01 Existing Product Order", "CHAIN-01 Commande Produit Existant"),
    ("CHAIN-02 Tooling Modification Order", "CHAIN-02 Modification Outillage"),
    ("CHAIN-03 New Tooling Order", "CHAIN-03 Nouvel Outillage"),
    ("CHAIN-04 Sourcing Order", "CHAIN-04 Commande Sourcing"),
    ("General Process Chain", "Chaine de Processus Generale"),
    ("Existing Product Order (CHAIN-01)", "Commande Produit Existant (CHAIN-01)"),
    ("Existing Product", "Produit Existant"),

    # BLOC detail steps
    ("Download order", "Telecharger la commande"),
    ("Save in ORDER_20XX", "Sauver dans COMMANDE_20XX"),
    ("Identify order type", "Identifier type de commande"),
    ("Route to chain", "Aiguiller vers chaine"),
    ("Create order sheet", "Creer fiche de commande"),
    ("Attach order PDF", "Joindre PDF commande"),
    ("Customer, date, deadline", "Client, date, delai"),
    ("Product selection", "Selection produit"),
    ("Ordered quantity", "Quantite commandee"),
    ("Final qty = identical", "Qte finale = identique"),
    ("Order ref = customer ref", "Ref commande = ref client"),
    ("Create transport sheet", "Creer fiche de transport"),
    ("Delivery delay validation", "Validation delai livraison"),
    ("Delivery type", "Type de livraison"),
    ("Define order status", "Definir statut commande"),
    ("Send info to suppliers", "Envoyer info aux fournisseurs"),
    ("Production delay validation", "Validation delai production"),
    ("Print acknowledgment", "Imprimer accuse de reception"),
    ("Send to customer", "Envoyer au client"),
    ("Customer response", "Reponse client"),
    ("Confirm production", "Confirmer production"),
    ("Progress tracking", "Suivi avancement"),
    ("Plan inspections", "Planifier inspections"),
    ("Conformity validation", "Validation conformite"),
    ("Release decision", "Decision de liberation"),
    ("Create delivery note", "Creer bon de livraison"),
    ("Supplier specifics", "Specificites fournisseur"),
    ("Customs tracking", "Suivi douane"),
    ("Commercial invoice", "Facture commerciale"),
    ("Inform customer", "Informer le client"),
    ("Conformity email", "Email conformite"),
    ("Send invoice", "Envoyer facture"),
    ("Payment customer", "Paiement client"),
    ("Close file", "Cloturer dossier"),

    # Navigation
    ("Back to Overview", "Retour Vue d'Ensemble"),
    ("Back to Chain", "Retour Chaine"),
    ("Back to BLOC", "Retour BLOC"),
    ("View Complete Process Chain", "Voir la Chaine de Processus Complete"),
    ("LEGEND", "LEGENDE"),
    ("Management — Management Process", "Direction — Processus de Management"),
    ("Commercial (SALES) — P01", "Commercial (VENTES) — P01"),
    ("Procurement (MANUFACTURE) — P02", "Achats (FABRICATION) — P02"),
    ("Logistics (DELIVERY) — P04", "Logistique (LIVRAISON) — P04"),
    ("Quality (QUALITY) — P03", "Qualite (QUALITE) — P03"),
    ("Support — PS01, PS02, PS03", "Support — PS01, PS02, PS03"),
    ("Orange border = General Process Chain Bloc (clickable)", "Bordure orange = Bloc Chaine Processus (cliquable)"),

    # Inter-swimlane labels
    ("Manufacturing", "Fabrication"),
    ("Transport", "Transport"),
    ("Delay feedback", "Retour delais"),
    ("Confirmation", "Confirmation"),
    ("QC Validation", "Validation QC"),
    ("Release", "Liberation"),
    ("Docs", "Docs"),
    ("Closure", "Cloture"),

    # BLOC detail page titles
    ("ORDER RECEPTION", "RECEPTION COMMANDE"),
    ("ORDER SHEET CREATION", "CREATION FICHE COMMANDE"),
    ("TRANSPORT SHEET CREATION", "CREATION FICHE TRANSPORT"),
    ("TECHNICAL STUDY SUPPLIERS", "ETUDE TECHNIQUE FOURNISSEURS"),
    ("ORDER VALIDATION", "VALIDATION COMMANDE"),
    ("PRODUCTION &amp;amp; QUALITY", "PRODUCTION &amp;amp; QUALITE"),
    ("DELIVERY &amp;amp; CUSTOMS", "LIVRAISON &amp;amp; DOUANE"),
    ("GOODS ACCEPTANCE &amp;amp; CLOSURE", "ACCEPTATION MARCHANDISE &amp;amp; CLOTURE"),

    # SUB-BLOC titles
    ("SUB-BLOC 1 - Order Reception", "SOUS-BLOC 1 - Reception Commande"),
    ("SUB-BLOC 2 - Order Sheet", "SOUS-BLOC 2 - Fiche Commande"),
    ("SUB-BLOC 3 - Transport Sheet", "SOUS-BLOC 3 - Fiche Transport"),
    ("SUB-BLOC 4 - Technical Study", "SOUS-BLOC 4 - Etude Technique"),
    ("SUB-BLOC 5 - Order Validation", "SOUS-BLOC 5 - Validation Commande"),
    ("SUB-BLOC 6 - Production &amp;amp; Quality", "SOUS-BLOC 6 - Production &amp;amp; Qualite"),
    ("SUB-BLOC 6 - Production &amp; Quality", "SOUS-BLOC 6 - Production &amp; Qualite"),
    ("SUB-BLOC 7 - Delivery &amp;amp; Customs", "SOUS-BLOC 7 - Livraison &amp;amp; Douane"),
    ("SUB-BLOC 7 - Delivery &amp; Customs", "SOUS-BLOC 7 - Livraison &amp; Douane"),
    ("SUB-BLOC 8 - Goods Acceptance", "SOUS-BLOC 8 - Acceptation Marchandise"),

    # Role labels
    ("Management Role", "Role Direction"),
    ("Commercial Role", "Role Commercial"),
    ("Procurement Role", "Role Achats"),
    ("Logistics Role", "Role Logistique"),
    ("Quality Role", "Role Qualite"),

    # Misc
    ("Associated documents:", "Documents associes:"),
    ("ISO reference:", "Reference ISO:"),
    ("View sub-details", "Voir sous-details"),
    ("(Active sheet)", "(Fiche active)"),
    ("(To be completed)", "(A completer)"),
    ("Existing Product Order", "Commande Produit Existant"),
    ("Tooling Modification Order", "Modification Outillage"),
    ("New Tooling Order", "Nouvel Outillage"),
    ("Sourcing Order", "Commande Sourcing"),
    ("ORDER TYPE", "TYPE DE COMMANDE"),
]

def translate(content):
    for en, fr in TRANSLATIONS:
        content = content.replace(en, fr)
    return content

if __name__ == "__main__":
    import sys
    src = "/home/user/ISO/v0.7/diagrammes/vue_ensemble_interactive_v3.drawio"
    with open(src, 'r', encoding='utf-8') as f:
        content = f.read()

    translated = translate(content)

    with open(src, 'w', encoding='utf-8') as f:
        f.write(translated)

    print(f"Translated {src} to French")
    print(f"Applied {len(TRANSLATIONS)} translation rules")
